### ISSUE TITLE
Archivable & concrete inheritance issue: archive table missing descendant_class column.

### ISSUE THREAD

**Issue by scepticalcat** [propelorm/Propel#278]
```
asset:
  _propel_behaviors:
    archivable: ~
  id:              ~
  filename: ~

typed_asset:
  _propel_behaviors:
    concrete_inheritance: { extends: asset }
  title: ~

sub_typed_asset:
  _propel_behaviors:
    concrete_inheritance: { extends: typed_asset }
  sub_title: ~
```

Using the above structure, were you to call $sub_typed_asset->delete() you would receive "Call to undefined method: setDescendantClass" from line 1317 of the BaseObjectClass as the typed_asset_archive table does NOT have a descendant_class column & hence has no setDescendantClass method.
