### ISSUE TITLE
Build problem with archivable child by concrete_inheritance

### ISSUE THREAD

**Issue by mrackwitz** [propelorm/Propel#366]
```
parent:
  id:   ~
  name: ~

child:
  _propel_behaviors:
    concrete_inheritance: { extends: asset }
    archivable: ~
  description: ~
```

If you build this schema for a MySQL database, you will get a NullPointerException from the following snippet where $column is null:

```
MysqlPlattform::getColumnBindingPHP: 622:
if ($column->getPDOType() == PDO::PARAM_BOOL) {
```

This is called by:

```
QueryBuilder::addFindPkSimple: 483:
$pk = $table->getPrimaryKey();
$column = $pk[0];
$script .= $platform->getColumnBindingPHP($column, "':p0'", "\$key", '          ');
```

My suspicion was, that this combination is rather untested and that the behaviors are not applied in the right order. So I modified the ArchivableBehavior.php like so:

```
class ArchivableBehavior extends Behavior
{
    protected $tableModificationOrder = 60; // after concrete_inheritance!
```

This solves the build problem, but seems to cause other bugs, when inserting the schema into the database.

P.S: This is not the same as #278.
