### ISSUE TITLE
Queries using select() will ignore rows with zero (0) or null values

### ISSUE THREAD

**Issue by latourfl** [propelorm/Propel#645]
If, for a given column, there are some rows where that column has values of zero or null, then using a select() query on that column will ignore those rows.

For example, using this schema:

```
test:
    _attributes: { phpName: Test, idMethod: native }
    id: { phpName: Id, type: INTEGER, sqlType: 'int(11) unsigned', primaryKey: true, autoIncrement: true, required: true }
    value: { phpName: Value, type: INTEGER, required: false }
```

and the following values entered in the database:

```
id  value
1   2
2   3
3   0
4   2
5   0
6   NULL
```

then the following query:

```
TestQuery::create()->select('Value')->find()
```

will return this:

```
PropelArrayCollection Object
(
    [0] => 2
    [1] => 3
    [2] => 2
)
```
