### ISSUE TITLE
inheritance behavior ignores baseClass attribute.

### ISSUE THREAD

**Issue by bassim** [propelorm/Propel#73]
I am defining something like:

```
child:
  _attributes: { baseClass: MyBaseChild }
  name: { type: VARCHAR, size: '255'  required: false, description: 'The object' }
  _propel_behaviors:
    concrete_inheritance:
      extends: parent
```

I'd like and expect BaseChild to extend MyBaseChild, not Parent.
