### ISSUE TITLE
SQL error after updating to propel1.6

### ISSUE THREAD

**Issue by ibr** [propelorm/Propel#8]
Propel 1.5.6: generated SQL is ok

``` sql
SELECT DISTINCT mateam.ID,.. mabfw.ID_MA, ... FROM mateam CROSS JOIN
mabfw_rollen LEFT JOIN mabfw ON (mateam.ID_MA=mabfw.ID_MA)
```

Propel 1.6.0 - [wrapped: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mabfw.ID_MA' in 'on clause']

``` sql
SELECT DISTINCT mateam.ID, ... mabfw.ID_MA, ... FROM mateam INNER
JOIN mabfw_rollen ON (mabfw.ID_MA=mabfw_rollen.ID_MA) LEFT JOIN mabfw
ON (mateam.ID_MA=mabfw.ID_MA)
```

Criteria used:

``` php
$auswahl->addJoin(MabfwPeer::ID_MA, MabfwRollenPeer::ID_MA);
$auswahl->setDistinct();
$Team->getMateamsJoinMabfw($auswahl)
```

Following the relevant part of the Schema:

``` yaml
mabfw:
    _attributes: { phpName: Mabfw }
    id_ma: { phpName: IdMa, type: VARCHAR, size: '20', primaryKey: true, required: true }
    name: { phpName: Name, type: VARCHAR, size: '30', required: false }
    vorname: { phpName: Vorname, type: VARCHAR, size: '30', required: false }
    passwort: { phpName: Passwort, type: VARCHAR, size: '60', required: false }

mabfw_rollen:
    _attributes: { phpName: MabfwRollen }
    id_ma: { phpName: IdMa, type: VARCHAR, size: '20', required: true, foreignTable: mabfw, foreignReference: id_ma, onDelete: RESTRICT, onUpdate: RESTRICT }
    id_rolle: { phpName: IdRolle, type: INTEGER, size: '10', required: true, defaultValue: '0', foreignTable: marollen, foreignReference: id_rolle}
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    _indexes: { id_ma: [id_ma] }
    _uniques: { id_ma_2: [id_ma, id_rolle] }

mateam:
    _attributes: { phpName: Mateam }
    id: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    id_team: { phpName: IdTeam, type: INTEGER, size: '11', required: true, foreignTable: team, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    id_ma: { phpName: IdMa, type: CHAR, size: '20', required: true, foreignTable: mabfw, foreignReference: id_ma, onDelete: RESTRICT, onUpdate: RESTRICT }
    verantwortlich: { phpName: Verantwortlich, type: TINYINT, size: '4', required: true, defaultValue: '0' }
    _indexes: { id_ma: [id_ma] }
    _uniques: { id_team: [id_team, id_ma] }
```

Also a rewrite with Propel Queries instead of the old Criterias was not successful:

Query used:

``` php
$q = MabfwRollenQuery::create()
->useMabfwQuery()
->useMateamQuery()
->orderByVerantwortlich('DESC')
->endUse()
->orderByName('ASC')
->endUse()
->setDistinct()
->find();
```

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mateam.ID_MA'
in 'on clause'

``` sql
SELECT DISTINCT mateam.ID, ..., mabfw.ID_MA FROM `mabfw_rollen` LEFT
JOIN `mabfw` ON (mateam.ID_MA=mabfw.ID_MA)INNER JOIN `mateam` ON
(mabfw.ID_MA=mateam.ID_MA) ORDER BY mateam.VERANTWORTLICH DESC,
mabfw.NAME ASC
```

Seems to be related with http://trac.propelorm.org/changeset/1959 and http://trac.propelorm.org/changeset/2049

Copy of http://www.propelorm.org/ticket/1382
